### PR TITLE
Migrates flatbuffers SPM to use google

### PR DESCRIPTION
**Pull request by mustiikhalil**
Migrates flatbuffers SPM to use google repository instead of the current one, since we decided to move everything there.

### CODE REVIEW

**Comment by mustiikhalil** [comment]
@liuliu seems that I broke main, we can revet until I figure out how to regenerate the code

**Comment by mustiikhalil** [comment]
I can't seem to make it build, I'll look into it tomorrow morning

**Comment by liuliu** [comment]
No worries. I will take a look and fix forward.

**Comment by liuliu** [comment]
Should be fixed :) Seems FlatBuffers Swift is pretty stable nowadays, I definitely encountered much more issues before when upgrading.

**Pull request merged**
